datasource:
  default: ${APP_ENV}
  development:
    username: "dev"
    password: "password"
    url: "jdbc:h2:./database"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

ebean:
  ddl:
    run: true
    generate: true
    migration:
      run: true