-- apply changes
create table urls (
  id                            bigint generated by default as identity not null,
  name                          varchar(255) not null,
  created_at                    timestamp not null,
  constraint pk_urls primary key (id)
);

create table url_checks (
  id                            bigint generated by default as identity not null,
  status_code                   integer,
  title                         clob,
  h1                            clob,
  description                   clob,
  url_id                        bigint not null,
  created_at                    timestamp not null,
  constraint pk_url_checks primary key (id)
);

-- foreign keys and indices
create index ix_url_checks_url_id on url_checks (url_id);
alter table url_checks add constraint fk_url_checks_url_id foreign key (url_id) references urls (id) on delete restrict on update restrict;

